import "./globals.css";

import { Inter } from "next/font/google";
import Provider from "./provider";
import { Spotlight } from "@/components/ui/spotlight-new";
import { GridPattern } from "@/components/magicui/grid-pattern";
import { cn } from "@/lib/utils";
import Starfield from "@/components/ui/starfield";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "optifire's planet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head>
        <Script src="/oneko.js" />
      </head>
      <body
        className={`${inter.className} overflow-x-hidden min-h-dvh antialiased`}
      >
        <Starfield
          starCount={1000}
          starColor={[255, 255, 255]}
          speedFactor={0.05}
          backgroundColor="black"
        />
        <Provider>
          <div className="container mx-auto min-h-screen flex flex-col justify-between py-20">
            <Spotlight />
            {children}
          </div>

          <footer className="container mx-auto flex flex-col justify-between py-20">

            <p className="text-6xl">Boo!</p>
          </footer>
        </Provider>
      </body>
    </html>
  );
}
